version: '3.3'

services:
  frontend:
    image: realisticcode/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/build:/build
    ports:
      - "12380:3000"
    restart: always
  nginx:
    image: realisticcode/nginx:latest
    build: ./nginx
    volumes:
      - ./frontend/out/:/frontend/out
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
