version: '3.3'

services:
  frontend:
    image: 24hlimes/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/build:/build
    ports:
      - "2480:3000"
    restart: always
  nginx:
    image: 24hlimes/nginx:latest
    build: ./nginx
    volumes:
      - ./frontend/out/:/frontend/out
    ports:
      - "2480:80"
      - "24443:443"
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
